DROP TABLE IF EXISTS USERS, GENRES, RATING_MPA, FILMS, FILM_GENRE, LIKES, FRIENDS_STATUS;

CREATE TABLE IF NOT EXISTS USERS (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(255),
    login varchar(255),
    name varchar(255),
    birthday date
    );

CREATE TABLE IF NOT EXISTS GENRES (
    genre_id int PRIMARY KEY,
    genre varchar(255)
    );

CREATE TABLE IF NOT EXISTS RATING_MPA (
    mpa_id int PRIMARY KEY,
    mpa_name varchar(255)
    );

CREATE TABLE IF NOT EXISTS FILMS (
    film_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255),
    description varchar(255),
    release_date date,
    duration int,
    mpa_id int REFERENCES RATING_MPA (mpa_id)
    );

CREATE TABLE IF NOT EXISTS FILM_GENRE (
    film_id bigint REFERENCES FILMS (film_id),
    genre_id int REFERENCES GENRES (genre_id)
    );

CREATE TABLE IF NOT EXISTS LIKES (
    user_id bigint REFERENCES USERS (user_id),
    film_id bigint REFERENCES FILMS (film_id)
    );

CREATE TABLE IF NOT EXISTS FRIENDS_STATUS (
    user_id bigint REFERENCES USERS (user_id),
    friend_id bigint REFERENCES USERS (user_id),
    approved boolean
    );